version: '3.8'

services:
  astro-server:
    build:
      context: ./astro-server
      dockerfile: Dockerfile
    expose:
      - "4321"
    restart: unless-stopped

  varnish:
    build:
      context: ./varnish-cache
      dockerfile: Dockerfile
    ulimits:
      memlock: -1
    expose:
      - "4322:80"
    environment:
      - VARNISH_PURGE_TOKEN=${VARNISH_PURGE_TOKEN}
    tmpfs:
      - /var/lib/varnish/varnishd:exec
