services:
  etlegacy-stats-astro:
    build:
      context: ./astro-server
      dockerfile: Dockerfile
    expose:
      - "4321"
    restart: unless-stopped

  etlegacy-stats-isenkram:
    build:
      context: ./isenkram
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./proxy.json:/app/proxy.json
    command: ["isenkram", "--config", "/app/proxy.json"]
