services:
  etlegacy-stats-astro:
    build:
      context: ./astro-server
      dockerfile: Dockerfile
    expose:
      - "4321"
    restart: unless-stopped

  etlegacy-stats-nginx:
    image: nginx:alpine
    expose:
      - "80"
    volumes:
      - ./nginx-config/conf.d:/etc/nginx/conf.d
    depends_on:
      - etlegacy-stats-astro
    restart: unless-stopped
