version: '3.8'

services:
  astro-server:
    build:
      context: ./astro-server
      dockerfile: Dockerfile
    expose:
      - "4321"
    restart: unless-stopped

  varnish:
    image: varnish
    ports:
      - "4322:80"
    volumes:
      - ./varnish-cache/default.vcl:/etc/varnish/default.vcl:ro
    tmpfs:
      - /var/lib/varnish/varnishd:exec
